### YamlMime:ManagedReference
items:
- uid: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider"
  id: "BaseDatabaseAccountConfigurationProvider"
  parent: "com.azure.cosmos.internal"
  children:
  - "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.BaseDatabaseAccountConfigurationProvider(com.azure.cosmos.DatabaseAccount,com.azure.cosmos.ConsistencyLevel)"
  - "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getMaxReplicaSetSize()"
  - "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getQueryEngineConfiguration()"
  - "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getStoreConsistencyPolicy()"
  langs:
  - "java"
  name: "BaseDatabaseAccountConfigurationProvider"
  nameWithType: "BaseDatabaseAccountConfigurationProvider"
  fullName: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider"
  type: "Class"
  package: "com.azure.cosmos.internal"
  summary: "Used internally to provides functionality to work with database account configuration in the Azure Cosmos DB database service."
  syntax:
    content: "public class BaseDatabaseAccountConfigurationProvider implements DatabaseAccountConfigurationProvider"
  inheritance:
  - "java.lang.Object"
  implements:
  - "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider"
  inheritedMembers:
  - "java.lang.Object.clone()"
  - "java.lang.Object.equals(java.lang.Object)"
  - "java.lang.Object.finalize()"
  - "java.lang.Object.getClass()"
  - "java.lang.Object.hashCode()"
  - "java.lang.Object.notify()"
  - "java.lang.Object.notifyAll()"
  - "java.lang.Object.toString()"
  - "java.lang.Object.wait()"
  - "java.lang.Object.wait(long)"
  - "java.lang.Object.wait(long,int)"
- uid: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.BaseDatabaseAccountConfigurationProvider(com.azure.cosmos.DatabaseAccount,com.azure.cosmos.ConsistencyLevel)"
  id: "BaseDatabaseAccountConfigurationProvider(com.azure.cosmos.DatabaseAccount,com.azure.cosmos.ConsistencyLevel)"
  parent: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider"
  langs:
  - "java"
  name: "BaseDatabaseAccountConfigurationProvider(DatabaseAccount databaseAccount, ConsistencyLevel desiredConsistencyLevel)"
  nameWithType: "BaseDatabaseAccountConfigurationProvider.BaseDatabaseAccountConfigurationProvider(DatabaseAccount databaseAccount, ConsistencyLevel desiredConsistencyLevel)"
  fullName: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.BaseDatabaseAccountConfigurationProvider(DatabaseAccount databaseAccount, ConsistencyLevel desiredConsistencyLevel)"
  overload: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.BaseDatabaseAccountConfigurationProvider*"
  type: "Constructor"
  package: "com.azure.cosmos.internal"
  syntax:
    content: "public BaseDatabaseAccountConfigurationProvider(DatabaseAccount databaseAccount, ConsistencyLevel desiredConsistencyLevel)"
    parameters:
    - id: "databaseAccount"
      type: "com.azure.cosmos.DatabaseAccount"
    - id: "desiredConsistencyLevel"
      type: "com.azure.cosmos.ConsistencyLevel"
- uid: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getMaxReplicaSetSize()"
  id: "getMaxReplicaSetSize()"
  parent: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider"
  langs:
  - "java"
  name: "getMaxReplicaSetSize()"
  nameWithType: "BaseDatabaseAccountConfigurationProvider.getMaxReplicaSetSize()"
  fullName: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getMaxReplicaSetSize()"
  overload: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getMaxReplicaSetSize*"
  type: "Method"
  package: "com.azure.cosmos.internal"
  syntax:
    content: "public int getMaxReplicaSetSize()"
    return:
      type: "int"
- uid: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getQueryEngineConfiguration()"
  id: "getQueryEngineConfiguration()"
  parent: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider"
  langs:
  - "java"
  name: "getQueryEngineConfiguration()"
  nameWithType: "BaseDatabaseAccountConfigurationProvider.getQueryEngineConfiguration()"
  fullName: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getQueryEngineConfiguration()"
  overload: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getQueryEngineConfiguration*"
  type: "Method"
  package: "com.azure.cosmos.internal"
  syntax:
    content: "public String getQueryEngineConfiguration()"
    return:
      type: "java.lang.String"
- uid: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getStoreConsistencyPolicy()"
  id: "getStoreConsistencyPolicy()"
  parent: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider"
  langs:
  - "java"
  name: "getStoreConsistencyPolicy()"
  nameWithType: "BaseDatabaseAccountConfigurationProvider.getStoreConsistencyPolicy()"
  fullName: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getStoreConsistencyPolicy()"
  overload: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getStoreConsistencyPolicy*"
  type: "Method"
  package: "com.azure.cosmos.internal"
  syntax:
    content: "public ConsistencyLevel getStoreConsistencyPolicy()"
    return:
      type: "com.azure.cosmos.ConsistencyLevel"
references:
- uid: "com.azure.cosmos.DatabaseAccount"
  name: "DatabaseAccount"
  nameWithType: "DatabaseAccount"
  fullName: "com.azure.cosmos.DatabaseAccount"
- uid: "com.azure.cosmos.ConsistencyLevel"
  name: "ConsistencyLevel"
  nameWithType: "ConsistencyLevel"
  fullName: "com.azure.cosmos.ConsistencyLevel"
- uid: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.BaseDatabaseAccountConfigurationProvider*"
  name: "BaseDatabaseAccountConfigurationProvider"
  nameWithType: "BaseDatabaseAccountConfigurationProvider.BaseDatabaseAccountConfigurationProvider"
  fullName: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.BaseDatabaseAccountConfigurationProvider"
  package: "com.azure.cosmos.internal"
- uid: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getStoreConsistencyPolicy*"
  name: "getStoreConsistencyPolicy"
  nameWithType: "BaseDatabaseAccountConfigurationProvider.getStoreConsistencyPolicy"
  fullName: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getStoreConsistencyPolicy"
  package: "com.azure.cosmos.internal"
- uid: "int"
  spec.java:
  - uid: "int"
    name: "int"
    fullName: "int"
- uid: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getMaxReplicaSetSize*"
  name: "getMaxReplicaSetSize"
  nameWithType: "BaseDatabaseAccountConfigurationProvider.getMaxReplicaSetSize"
  fullName: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getMaxReplicaSetSize"
  package: "com.azure.cosmos.internal"
- uid: "java.lang.String"
  spec.java:
  - uid: "java.lang.String"
    name: "String"
    fullName: "java.lang.String"
- uid: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getQueryEngineConfiguration*"
  name: "getQueryEngineConfiguration"
  nameWithType: "BaseDatabaseAccountConfigurationProvider.getQueryEngineConfiguration"
  fullName: "com.azure.cosmos.internal.BaseDatabaseAccountConfigurationProvider.getQueryEngineConfiguration"
  package: "com.azure.cosmos.internal"
- uid: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider"
  name: "DatabaseAccountConfigurationProvider"
  nameWithType: "DatabaseAccountConfigurationProvider"
  fullName: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider"
- uid: "java.lang.Object.notify()"
  name: "Object.notify()"
  nameWithType: "Object.notify()"
  fullName: "java.lang.Object.notify()"
- uid: "java.lang.Object.wait()"
  name: "Object.wait()"
  nameWithType: "Object.wait()"
  fullName: "java.lang.Object.wait()"
- uid: "java.lang.Object.finalize()"
  name: "Object.finalize()"
  nameWithType: "Object.finalize()"
  fullName: "java.lang.Object.finalize()"
- uid: "java.lang.Object.clone()"
  name: "Object.clone()"
  nameWithType: "Object.clone()"
  fullName: "java.lang.Object.clone()"
- uid: "java.lang.Object.notifyAll()"
  name: "Object.notifyAll()"
  nameWithType: "Object.notifyAll()"
  fullName: "java.lang.Object.notifyAll()"
- uid: "java.lang.Object.equals(java.lang.Object)"
  name: "Object.equals(Object)"
  nameWithType: "Object.equals(Object)"
  fullName: "java.lang.Object.equals(java.lang.Object)"
- uid: "java.lang.Object.getClass()"
  name: "Object.getClass()"
  nameWithType: "Object.getClass()"
  fullName: "java.lang.Object.getClass()"
- uid: "java.lang.Object.wait(long)"
  name: "Object.wait(long)"
  nameWithType: "Object.wait(long)"
  fullName: "java.lang.Object.wait(long)"
- uid: "java.lang.Object.hashCode()"
  name: "Object.hashCode()"
  nameWithType: "Object.hashCode()"
  fullName: "java.lang.Object.hashCode()"
- uid: "java.lang.Object.wait(long,int)"
  name: "Object.wait(long,int)"
  nameWithType: "Object.wait(long,int)"
  fullName: "java.lang.Object.wait(long,int)"
- uid: "java.lang.Object.toString()"
  name: "Object.toString()"
  nameWithType: "Object.toString()"
  fullName: "java.lang.Object.toString()"
