### YamlMime:ManagedReference
items:
- uid: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider"
  id: "DatabaseAccountConfigurationProvider"
  parent: "com.azure.cosmos.internal"
  children:
  - "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getMaxReplicaSetSize()"
  - "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getQueryEngineConfiguration()"
  - "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getStoreConsistencyPolicy()"
  langs:
  - "java"
  name: "DatabaseAccountConfigurationProvider"
  nameWithType: "DatabaseAccountConfigurationProvider"
  fullName: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider"
  type: "Interface"
  package: "com.azure.cosmos.internal"
  summary: "Defines an interface to work with database account configuration in the Azure Cosmos DB database service."
  syntax:
    content: "public interface DatabaseAccountConfigurationProvider"
- uid: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getMaxReplicaSetSize()"
  id: "getMaxReplicaSetSize()"
  parent: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider"
  langs:
  - "java"
  name: "getMaxReplicaSetSize()"
  nameWithType: "DatabaseAccountConfigurationProvider.getMaxReplicaSetSize()"
  fullName: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getMaxReplicaSetSize()"
  overload: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getMaxReplicaSetSize*"
  type: "Method"
  package: "com.azure.cosmos.internal"
  syntax:
    content: "public abstract int getMaxReplicaSetSize()"
    return:
      type: "int"
- uid: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getQueryEngineConfiguration()"
  id: "getQueryEngineConfiguration()"
  parent: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider"
  langs:
  - "java"
  name: "getQueryEngineConfiguration()"
  nameWithType: "DatabaseAccountConfigurationProvider.getQueryEngineConfiguration()"
  fullName: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getQueryEngineConfiguration()"
  overload: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getQueryEngineConfiguration*"
  type: "Method"
  package: "com.azure.cosmos.internal"
  syntax:
    content: "public abstract String getQueryEngineConfiguration()"
    return:
      type: "java.lang.String"
- uid: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getStoreConsistencyPolicy()"
  id: "getStoreConsistencyPolicy()"
  parent: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider"
  langs:
  - "java"
  name: "getStoreConsistencyPolicy()"
  nameWithType: "DatabaseAccountConfigurationProvider.getStoreConsistencyPolicy()"
  fullName: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getStoreConsistencyPolicy()"
  overload: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getStoreConsistencyPolicy*"
  type: "Method"
  package: "com.azure.cosmos.internal"
  syntax:
    content: "public abstract ConsistencyLevel getStoreConsistencyPolicy()"
    return:
      type: "com.azure.cosmos.ConsistencyLevel"
references:
- uid: "com.azure.cosmos.ConsistencyLevel"
  name: "ConsistencyLevel"
  nameWithType: "ConsistencyLevel"
  fullName: "com.azure.cosmos.ConsistencyLevel"
- uid: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getStoreConsistencyPolicy*"
  name: "getStoreConsistencyPolicy"
  nameWithType: "DatabaseAccountConfigurationProvider.getStoreConsistencyPolicy"
  fullName: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getStoreConsistencyPolicy"
  package: "com.azure.cosmos.internal"
- uid: "int"
  spec.java:
  - uid: "int"
    name: "int"
    fullName: "int"
- uid: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getMaxReplicaSetSize*"
  name: "getMaxReplicaSetSize"
  nameWithType: "DatabaseAccountConfigurationProvider.getMaxReplicaSetSize"
  fullName: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getMaxReplicaSetSize"
  package: "com.azure.cosmos.internal"
- uid: "java.lang.String"
  spec.java:
  - uid: "java.lang.String"
    name: "String"
    fullName: "java.lang.String"
- uid: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getQueryEngineConfiguration*"
  name: "getQueryEngineConfiguration"
  nameWithType: "DatabaseAccountConfigurationProvider.getQueryEngineConfiguration"
  fullName: "com.azure.cosmos.internal.DatabaseAccountConfigurationProvider.getQueryEngineConfiguration"
  package: "com.azure.cosmos.internal"
